apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: readiness-probe-test-pdb
spec:
  minAvailable: 2
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      lbLabel: dummyLB
