apiVersion: v1
kind: Service
metadata:
  labels:
    release: readiness-probe-test
  name: readiness-probe-test
  namespace: default
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    lbLabel: dummyLB
  sessionAffinity: None
  type: ClusterIP
